// <auto-generated />
using Entites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entites.Migrations
{
    [DbContext(typeof(EquipeContext))]
    partial class EquipeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Entites.EquipeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomEquipe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomEquipe = "Manu"
                        },
                        new
                        {
                            Id = 2,
                            NomEquipe = "PSG"
                        });
                });

            modelBuilder.Entity("Entites.JoueurEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipeForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomJoueur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrenomJoueur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipeForeignKey");

                    b.ToTable("Joueurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipeForeignKey = 1,
                            NomJoueur = "Nom",
                            PrenomJoueur = "Prenom"
                        },
                        new
                        {
                            Id = 2,
                            EquipeForeignKey = 2,
                            NomJoueur = "Nom2",
                            PrenomJoueur = "Prenom2"
                        },
                        new
                        {
                            Id = 3,
                            EquipeForeignKey = 2,
                            NomJoueur = "Nom3",
                            PrenomJoueur = "Prenom3"
                        });
                });

            modelBuilder.Entity("Entites.JoueurEntity", b =>
                {
                    b.HasOne("Entites.EquipeEntity", "EquipeEntity")
                        .WithMany("Joueurs")
                        .HasForeignKey("EquipeForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipeEntity");
                });

            modelBuilder.Entity("Entites.EquipeEntity", b =>
                {
                    b.Navigation("Joueurs");
                });
#pragma warning restore 612, 618
        }
    }
}
